#!/bin/bash

#for sam... my imaginary tmate friend
alias vi=vim

# aws
alias av='aws-vault-exec'
alias avl='aws-vault exec -d 12h jeremy true'
alias ecsl='ecs-cli logs --task-id'
alias ec2s='aws ssm start-session --target'

#Docker Docker Docker Docker Docker Docker Docker Docker Docker
alias doc=docker
alias d=docker
alias dx='docker exec'
alias dps='docker ps'
alias cmp=docker-compose
alias dma=docker-machine
alias dsav=docker-set-api-version
alias dv='docker volume'
alias dq='docker run -it --rm'

alias k=kubectl
alias kak='kubectl apply -k'
alias kk='kubectl kustomize'
alias h=helm
alias tf=terraform
alias os=openstack

#git
alias gca\!='git commit --amend'
alias gs='git status'
alias gsur='git submodule update --init --recursive'
alias gcb\!='git checkout -B'
alias gct='git checkout -t'
alias gct\!='git checkout -f -t'
alias gma='git merge --abort'
alias gcn='git clean -n'
alias gcn\!='git clean -f'
alias gpu\!='git-push-bravely'
alias ghcl='git-clone-private'
alias gbu='git branch --set-upstream-to'
alias grh='git reset --hard'
alias grk='git reset --keep'
alias gpr='git-setup-pullrequest-branch'
alias gpr\!='git-close-pullrequest-branch'
alias git-clean-merged-branches='git branch -D $(git branch --merged | tail -n +2)'
alias what-is-upstream='git rev-parse --abbrev-ref --symbolic-full-name @{u}'
alias wiu='what-is-upstream'
alias gbdp="echo local branches to delete:;git branch -vv | grep 'origin/.*: gone\]' | awk '{print \$1}'"
alias gbdp\!="git branch -vv | grep 'origin/.*: gone\]' | awk '{print \$1}' | xargs git branch -D"
alias grc="git for-each-ref --sort=-committerdate --format='%(objectname:short) -> %(refname:short)'|head -n10"
alias grcl="git for-each-ref --sort=-committerdate --format='%(objectname:short) -> %(refname:short)'|less"

unalias gb  #oh-my-zsh uses this, but gb is a go tool, so conflict!
unalias gclean  #I deem this unsafe atm. It's only safe 80% of the time...

if which stat 2>/dev/null 1>/dev/null ; then
  alias d.="desk ."
fi

alias tmux="TERM=screen-256color-bce tmux"
#old skool, non-brew install on osx
alias woman=eg
