#!/bin/bash

#Docker Docker Docker Docker Docker Docker Docker Docker Docker
alias doc=docker
alias d=docker
alias dx='docker exec'
alias dps='docker ps'
alias cmp=docker-compose
alias dma=docker-machine

alias tf=terraform
alias os=openstack

#git
alias gs='git status'
alias gcn='git clean -n'
alias gcn\!='git clean -f'
alias gpu\!='git-push-bravely'
alias ghcl='git-clone-private'
alias gpr='git-setup-pullrequest-branch'
alias gpr\!='git-close-pullrequest-branch'
alias what-is-upstream='git rev-parse --abbrev-ref --symbolic-full-name @{u}'

unalias gb  #oh-my-zsh uses this, but gb is a go tool, so conflict!
unalias gclean  #I deem this unsafe atm. It's only safe 80% of the time...


alias gws="PATH=/usr/local/opt/coreutils/libexec/gnubin:usr/local/opt/gnu-sed/libexec/gnubin:$PATH $HOME/bin/gws"
alias woman=eg
