#!/bin/bash
# vi mode
set -o vi
bindkey '^R' history-incremental-search-backward

# docker
# if docker-machine status dev ; then
#     eval $(docker-machine env dev)
# fi
DOCKER_VIM_IMAGE=dudymas/toolbox

# dnvm
if which dnvm.sh 2>/dev/null >/dev/null ; then
    source $(which dnvm.sh)
    if dnvm list >/dev/null; then
      #dnvm use ${DNVM_RUNTIME_VERSION:-1.0.0-rc2-20221} -r coreclr >/dev/null
    fi
fi

# powerline
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
source ~/.ghq/github.com/powerline/powerline/powerline/bindings/zsh/powerline.zsh

# deis/fleet
if [ -e $HOME/fleet.json ] ; then
    export FLEETCTL_TUNNEL=$(jq .fleetctl.tunnel $HOME/fleet.json -r)
fi

if [ -e $HOME/deis.json ] ; then
    export DEISCTL_TUNNEL=$(jq .deis.tunnel $HOME/fleet.json -r)
fi

# venv
#export WORKON_HOME=$HOME/.virtualenvs
#export PROJECT_HOME=$HOME/Code/projects
if which virtualenvwrapper_lazy.sh 2>/dev/null >/dev/null ; then
  source $(which virtualenvwrapper_lazy.sh)
fi

#generic avi's
. $SCRIPT_DIR/api.keys

MARKER_DAT_JUNK=$HOME/.local/share/marker/marker.sh
if [ -e "$MARKER_DAT_JUNK" ] ; then
  [[ -s "$MARKER_DAT_JUNK" ]] && source "$MARKER_DAT_JUNK"
fi
