#!/bin/bash
# vi mode
set -o vi
bindkey '^R' history-incremental-search-backward

# docker
# if docker-machine status dev ; then
#     eval $(docker-machine env dev)
# fi
DOCKER_VIM_IMAGE=dudymas/toolbox

# ecs
export ECSSH_USER=jeremy

# starship
eval "$(starship init zsh)"

# venv
if which virtualenvwrapper_lazy.sh 2>/dev/null >/dev/null ; then
  source $(which virtualenvwrapper_lazy.sh)
fi
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export PYENV_HOOK_PATH=makeenv.sh

# NOTE, rustc and rvm have been moved to paths file atm

# direnv
eval "$(direnv hook zsh)"

# GPG foo
# uncomment if using a tty-style pinentry app
#export GPG_TTY=$(tty)
